"""added user_id for class RefreshToken in models.py

Revision ID: 24b938ec6557
Revises: 725907b036e0
Create Date: 2025-08-16 09:48:36.447899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b938ec6557'
down_revision: Union[str, Sequence[str], None] = '725907b036e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'refresh_token', 'userprofile', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_token', type_='foreignkey')
    op.drop_column('refresh_token', 'user_id')
    # ### end Alembic commands ###
