"""updated table names

Revision ID: 53f3063f7016
Revises: d3de19f44482
Create Date: 2025-08-16 09:25:09.668153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f3063f7016'
down_revision: Union[str, Sequence[str], None] = 'd3de19f44482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    op.drop_table('userprofile')
    op.drop_table('refresh_token')
    op.drop_table('review')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',

    )
    op.create_table('refresh_token',

    )
    op.create_table('userprofile',

    )
    op.create_table('property',

    )
    # ### end Alembic commands ###
